### ISSUE TITLE
Pantheon appservers don't have PHP tidy extension

### ISSUE THREAD

**Issue by dustinleblanc** [lando/pantheon#11]
Pantheon's appservers have the [html tidy](https://www.php.net/manual/en/intro.tidy.php) extension and Lando/Localdev does not, we should add this extension to the containers. See https://pantheon-community.slack.com/archives/CB2H8065D/p1595455998128500?thread_ts=1595449559.127700&cid=CB2H8065D

**Comment by reynoldsalec** [comment]
...this came up in a recent Slack convo. The proposal in https://github.com/lando/pantheon/issues/10 had been to move towards using "actual" Pantheon images for Lando, but I believe that hasn't been considered as an option for some time. I think we could build this into the Pantheon recipe another way...will have to look at this.

In the meantime, if you need tidy, an implementation using the `build_as_root` option for your site's `appserver` service should work. Add this to your `.lando.yml` file:

```
services:
  appserver:
    build_as_root:
      - apt-get update && apt-get install -y libtidy-dev && docker-php-ext-install tidy && docker-php-ext-enable tidy
```

I'm not 100% sure about libtidy versions/compatibility with PHP versions, so you may need to install a different package, but something like that should work!
