### ISSUE TITLE
Cannot Get Solr 3.6 to Work with Drupal 9

### ISSUE THREAD

**Issue by GuyPaddock** [lando/pantheon#113]
After upgrading to Drupal 9 with Search API Solr 4.x, we can't get Lando to communicate with the copy of Solr that comes with the Pantheon recipe. 

We're running the following:
- Lando v3.6.2
- Drupal Core v9.2.13
- Search API v1.23.0
- Search API Pantheon v3.0.1
- Search API Solr v4.2.7
- Search API Solr Legacy v4.2.7

With this configuration, on the `/admin/config/search/search-api/server/solr_pantheon` page, we get the following errors:
- "The Solr server could not be reached or is protected by your service provider."
- "The Solr core could not be accessed. Further data is therefore unavailable."

When performing searches, we get the following error as a status message:
```
An error occurred while trying to search with Solr: HTTP Status 404 – Not Found
body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} 
h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} 
a {color:black;} .line {height:1px;background-color:#525D76;border:none;}
HTTP Status 404 – Not FoundType Status ReportMessage 
/sites/self/environments/lando/index/solr/selectDescription 
The origin server did not find a current representation for the target resource or is not 
willing to disclose that one exists.Apache Tomcat/7.0.100 (Debian)
```

Our `lando.yml` looks like this:
```yaml
name: REDACTED
recipe: pantheon
config:
  framework: drupal8
  site: REDACTED
  id: REDACTED
  index: true
services:
  database:
    portforward: 3307
  appserver:
    xdebug: true
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
    config:
      php: .lando/php.ini
```

Our `pantheon.yml` looks like this:
```yaml
api_version: 1
web_docroot: true
php_version: 7.4
enforce_https: transitional
database:
  version: 10.4
drush_version: 10
search:
  version: 3
```

Our custom `.lando/php.ini` file looks like this:

```
xdebug.idekey = 'www-data'
xdebug.mode = debug
xdebug.client_host = ${LANDO_HOST_IP}

[PHP]
assert.exception = 1
```
