### ISSUE TITLE
File-sync issue between appserver and appserver_nginx container

### ISSUE THREAD

**Issue by jcowher** [lando/pantheon#121]
**Tell us about your setup**
Lando v3.6.4; macOS Monterey; Intel chip; Docker Desktop 3.6.0

**Tell us about your .lando.yml**
```yaml
name: 360pr
recipe: pantheon
config:
  framework: drupal8
  id: [omitted]
  site: 360pr
  index: false
  edge: false
  cache: false
services:
  appserver_nginx:
    scanner: false
  appserver:
    app_mount: false
    scanner: false
```

**Tell us about the command you were running**
Not applicable

**Tell us about the error you got**
None

**Summary**
I would like to start off by saying I am using a non-traditional setup of Lando and this issue only appears to happen when `app_mount: false`. I do this because I'm using a five year old Macbook Pro and disabling the app_mount speeds things up substantially. I use a bash command to rsync files to/from the Docker container as needed.

With that being said, when I upload an image via Drupal (v9.3) the image can't be found. For example, visiting `https://test.lndo.site/sites/default/files/2022-04/image.jpg` returns a 404 error. Strange thing is that if I run:

```bash
lando ssh -s appserver
ls -alh web/sites/default/files/2022-04
```

I can see the image there and with the correct file permissions and www-data as the owner/group.

If run...

```bash
lando ssh -s appserver_nginx
ls -alh web/sites/default/files/2022-04
```

... I don't see the image or it's parent `2022-04` directory. I am able to see all of the other non-uploaded files though such as `/app/composer.json`, `web/index.php`, etc.

If I remove...

```yaml
  appserver:
    app_mount: false
```

...images work as expected.

If add...

```yaml
excludes:
  - web/sites/default/files
```

... (with app_mount enabled) images work as expected.

I have also tried disabling the app_mount on the appserver_nginx service and rsyncing files to both appserver_nginx and appserver, but that just makes things worse and I start receiving 500 errors on every page.

```yaml
services:
  appserver_nginx:
    scanner: false
    app_mount: false
  appserver:
    app_mount: false
    scanner: false
```

It was worth mentioning that I was recently having a similar problem a WordPress recipe via NGINX so this might be something to do with the internal Docker connection between appserver and appserver_nginx and not this recipe specifically.

Thank you for all of the effort you put in Lando. It's an invaluable tool for me and the team I work with and we sincerely appreciate it!
