### ISSUE TITLE
Lando v3.14.0 -  Rebuild/Restart = Bad Gateways

### ISSUE THREAD

**Issue by philoSurfer** [lando/pantheon#160]

**Comment by philoSurfer** [comment]
Additional info: 

**.lando.yml**
```
name: SITENAME
recipe: pantheon
config:
  framework: drupal8
  site: SITENAME
  id: ID_HERE
```
  
**pantheon.yml**
```
api_version: 1
php_version: 7.4

workflows:
  deploy:
    after:
      - type: webphp
        description: Import configuration from .yml files
        script: private/scripts/drush_config_set.php
      - type: webphp
        description: Log to New Relic
        script: private/scripts/new_relic_deploy.php
  sync_code:
    after:
      - type: webphp
        description: Log to New Relic
        script: private/scripts/new_relic_deploy.php
```
