### ISSUE TITLE
Disable Scanner

### ISSUE THREAD

**Issue by spenceratwatson** [lando/pantheon#175]
How do I disable the scanner with a Pantheon Wordpress setup. This is my lando setup.

```yaml
name: testname
recipe: pantheon
config:
  framework: wordpress
  site: testname
  id: ????????????????????
proxy:
  appserver_nginx:
    - testname.lndo.site
  edge_ssl:
    - testname.lndo.site
scanner: false
```

**Comment by spenceratwatson** [comment]
Figured it out:

```
name: testname
recipe: pantheon
config:
  framework: wordpress
  site: testname
  id: ???????????
services:
  appserver_nginx:
    scanner: false
  edge:
    scanner: false
  edge_ssl:
    scanner: false
```
