### ISSUE TITLE
lando.yml portforward doesn't work

### ISSUE THREAD

**Issue by spencerthayer** [lando/pantheon#192]
This is a persistent issue already well documented in [Fixing DB port with portforward is not working lando/lando#39](https://github.com/lando/platformsh/issues/39) and [Locking down ports for external database connection not working](https://github.com/lando/platformsh/issues/171). So I don't feel I need to add additional documentation to this, but I should note that I too am experiencing this issue with the latest v3.11.0 installation but with a Pantheon configuration- not PlatformSH.

_I understand this isn't critical but are there any insights as to when this might be resolved?_

**Comment by lsmith77** [comment]
here is the full lando file. I am using plain lando (ie. not pantheon or platform.sh)

```
name: dashboard
recipe: laravel

proxy:
  appserver_nginx:
    - dashboard.lndo.site
  mailhog:
    - mail.lndo.site

services:
  database:
    portforward: 3307
  node:
    type: node:14
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver_nginx

tooling:
  npm:
    service: node
  node:
    service: node

config:
  via: nginx
  php: '8.0'
  composer_version: 2-latest
  xdebug: false
  webroot: public
  database: mariadb:10.5
```
