### ISSUE TITLE
Containers return 500 error after login

### ISSUE THREAD

**Issue by Phalconline** [lando/pantheon#256]
The last try was to delete docker and Lando and install them from scratch. 
**After lando start:**
![image](https://user-images.githubusercontent.com/3986432/63602773-e48fa780-c5d0-11e9-8aed-76fe23ae555c.png)

**Then I open all links:**
https://localhost:32800/ - ERR_TOO_MANY_REDIRECTS
![image](https://user-images.githubusercontent.com/3986432/63604109-a9db3e80-c5d3-11e9-8588-2395efb2a76f.png)
https://localhost:32801 - ERR_SSL_PROTOCOL_ERROR
https://localhost:32799/ - ERR_CONNECTION_CLOSED
http://website.lndo.site/ - OK - but after login, I have error 500 in the browser on the admin page
https://website.lndo.site/ - OK - but after login, I have error 500 in the browser on the admin page
https://localhost:32798 - OK

My **lando.yml**
```
name: website
recipe: pantheon
env_file: lando.env
config:
  env_file: lando.env
  framework: wordpress
  site: website
  id: my-id
  xdebug: true
  index: true
  edge: true
  cache: true
tooling:
  env:
    service: web
```

**Logs**
![image](https://user-images.githubusercontent.com/3986432/63603133-a646b800-c5d1-11e9-9116-e94a07380a1b.png)
![image](https://user-images.githubusercontent.com/3986432/63603144-ae9ef300-c5d1-11e9-98a9-b8f9b204e83f.png)
![image](https://user-images.githubusercontent.com/3986432/63603162-b78fc480-c5d1-11e9-8ed4-e7568a9188c3.png)
Also, that in **index** container: `WARNING: A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] does not meet these criteria and has been changed to []`

**macOS v.10.14.6**
**Docker Version 18.03.1-ce-mac64**
**Lando Pantheon recipe for wordpress**
**Lando & terminus version**
![image](https://user-images.githubusercontent.com/3986432/63602460-2b30d200-c5d0-11e9-95f5-205072b12e46.png)

I have a custom folder for wp-core, I use `core` instead `wp` 

Do you have any ideas what the problem or where I can found logs with the errors?
