### ISSUE TITLE
Cannot use lando pull

### ISSUE THREAD

**Issue by dchaffin** [lando/pantheon#272]
I just updated Lando to 3.23.3 and now I cannot use lando pull. When I try, it waits a few seconds and just returns to a command prompt. I've tried destroying, rebuilding, re-initing, etc. and I can't seem to figure it out. I'm not even sure what other information would be helpful here. 

.lando.yml

```
name: *********
recipe: pantheon
config:
  framework: drupal8
  webroot: web
  php: "8.3"
  site: *********
  id: *********
proxy:
  edge:
    - *********.lndo.site
tooling:
  drupal:
    cmd:
      - /app/vendor/bin/drupal
      - "--root=/app/web"
```

pantheon.yml

```
api_version: 1
web_docroot: true
php_version: 8.3
database:
  version: 10.4
enforce_https: full
workflows:
  deploy_product:
    after:
      -
        type: webphp
        description: 'Run composer prepare-for-pantheon'
        script: private/scripts/deploy_product/prepare-for-pantheon.php
      -
        type: webphp
        description: 'Run composer install & drupal-scaffold'
        script: private/scripts/deploy_product/composer-install.php
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php
```
