### ISSUE TITLE
Current master has all sql commands failing; db-import, db-export, pull, push; lando pull db fails for pantheon recipe

### ISSUE THREAD

**Issue by msschwartz** [lando/pantheon#54]
In our site the wordpress files are not inside the root directory (i.e. they exist in `/web`). When running `lando pull --database=dev --files=none --code=none` the command will fail at the end when replacing dev URLs with local URLs. 

*Error message*
```
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

*System*
v3.0.0-beta.36 on macOS Sierra

*.lando.yml*
```
name: super-awesome-site
recipe: pantheon
config:
  framework: wordpress
  site: super-awesome-site
  id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

*pantheon.yml*
```
api_version: 1
php_version: 5.6
web_docroot: true
```
