### ISSUE TITLE
Pantheon + Behat: Curl Error

### ISSUE THREAD

**Issue by chrisroane** [lando/pantheon#56]
I'm getting this curl error when I try to run a simple test:
https://www.dropbox.com/s/v19nda8c6vsrijw/Screenshot%202018-03-04%2016.44.06.png?dl=0

I searched the issue queue and the web with no luck. I was able to get a simple behat test running in lando using the vanilla drupal7 recipe, but I can't get it to work on this client site. 

**Here is the command I am using to run this test:**
```bash
lando behat tests/features/publication.featured-buckets.feature
@node-0 @api @javascript @MEDSTAT @MEDSTAT-PUBLICATION-BUCKETS
Feature: Featured Bucket system should display content properly
  In order to view publications
  As an anonymous user
  I should see correct slot system page

  Scenario: An anonymous user views a top 25 publication # tests/features/publication.featured-buckets.feature:8
    When I visit "/edermatologynews"                     # Drupal\DrupalExtension\Context\MinkContext::assertAtPath()
      Could not open connection: Curl error thrown for http POST to https://nginx:4444/wd/hub/session with params: {"desiredCapabilities":{"browserName":"firefox","version":"9","platform":"ANY","browserVersion":"9","browser":"firefox","name":"Behat feature suite","deviceOrientation":"portrait","deviceType":"tablet","selenium-version":"2.31.0","tags":["e263cdf94b2f","PHP 7.0.27"],"ignoreZoomSetting":false}}

      Failed to connect to nginx port 4444: Connection refused (Behat\Mink\Exception\DriverException)
    │
    ╳  Fatal error: Call to a member function screenshot() on null (Behat\Testwork\Call\Exception\FatalThrowableError)
    │
    └─ @AfterStep # ErrorHandlingContext::printLastResponseOnError()
    Then I should see a ".medstat-overview-page" element #
```

**.lando.yml**
```name: mdedge
recipe: pantheon
config:
  framework: drupal
  site: [site]
  id: [site-id]
  env: dev
  webroot: build
  xdebug: true
services:
  appserver:
    build:
      - "cd $LANDO_MOUNT && composer install"
      - "mkdir -p ~/.drush/site-aliases"
      - "ln -sf /app/drush/medstat.aliases.drushrc.php ~/.drush/site-aliases/medstat.aliases.drushrc.php"
    overrides:
      services:
        environment:
          BEHAT_PARAMS: >-
            {"extensions" : {"Behat\\MinkExtension" : {"base_url" :
            "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {
            "root":  "/app/build" }}}}
  phpmyadmin:
    type: phpmyadmin
  node:
    type: node:8.4
    build:
      - "cd $LANDO_MOUNT && npm install"
    globals:
      gulp-cli: "latest"
events:
  post-import-db:
    - echo "Obtaining database."
    - bash -c "test -f /app/db/tmp-db.sql.gz || terminus backup:get frontline-med.live --element=db --to=/app/db/tmp-db.sql.gz"
    - echo "Dropping old database."
    - drush @medstat.local sql-drop -y
    - echo "Importing database."
    - bash -c "gunzip -k < /app/db/tmp-db.sql.gz | drush @medstat.local sql-cli"
  post-import-db-fresh:
    - echo "Obtaining database."
    - bash -c "test -f /app/db/fresh-db.sql.gz || terminus backup:get frontline-med.fresh --element=db --to=/app/db/fresh-db.sql.gz"
    - echo "Dropping old database."
    - drush @medstat.local sql-drop -y
    - echo "Importing database."
    - bash -c "gunzip -k < /app/db/fresh-db.sql.gz | drush @medstat.local sql-cli"
  post-local:
    - drush @medstat.local dl registry_rebuild -n
    - drush @medstat.local rr
    - drush @medstat.local cc drush
    - drush @medstat.local en -y master
    - drush @medstat.local master-execute -y --scope=local
    - bash -c "drush @medstat.local updb -y || true"
    - drush @medstat.local fra -y
    - drush @medstat.local cc drush
tooling:
  drush:
    service: appserver
    cmd:
      - "drush"
      - "@medstat.local"
      - "--root=/app/build"
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  import-db-fresh:
    description: Import the fresh backup database.
    cmd: true
    service: appserver
  import-db:
    description: Import the live backup database.
    cmd: true
    service: appserver
  local:
    description: Clear drupal caches.
    cmd: true
    service: appserver
```

**behat.yml**
```
default:
  autoload:
    '': '%paths.base%/tests/features/bootstrap'
  gherkin:
    cache: ~
  formatters:
    pretty: true
  suites:
    default:
      paths: [ '%paths.base%/tests/features' ]
      filters:
        tags: ~@wip
      contexts:
        - MedstatFeatureContext
        - MedstatDrupalContext
        - MedstatRestfulContext:
            base_url: 'https://nginx'
            files_path: '%paths.base%/tests/assets'
            api_role: 'api write client'
        - ErrorHandlingContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      javascript_session: selenium2
      selenium2:
        wd_host: 'https://nginx:4444/wd/hub'
      base_url: 'https://nginx'
      files_path: '%paths.base%/tests/assets'
      sessions:
        default:
          goutte:
            guzzle_parameters:
              verify: false
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drupal:
        drupal_root: '/app/build'
      drush:
        alias: 'medstat.local'
      selectors:
        message_selector: '.messages'
        error_message_selector: '.messages.error'
        success_message_selector: '.messages.status'
      region_map:
        hidden_nav: '.nav-hidden'
        header: '#header'
```

Any tips you can give me in helping me get this to work? This is my first time using lando on a client project and I love everything about this project! Thanks for the help.
