### ISSUE TITLE
Importing database is extremely slow

### ISSUE THREAD

**Issue by generalredneck** [lando/pantheon#68]
**Tell us about your setup**

What is your lando version and operating system?
lando v3.0.0-beta.20
docker 17.09.0-ce
ubuntu Gnome 16.04.3 LTS 64-bit

**Tell us about your `.lando.yml`**

```yml
name: accme                                                                                                                                                                                                                                   
recipe: drupal7                                                                 
config:                                                                         
  webroot: ./web                                                                
  php: '5.6'
```

As a lando user, I would like databases to not take so long to import so that I can get more work done.

So I rebuild environments a lot. We are evaluating Lando as something to replace DrupalVM and I happened to notice that database imports seemed to take so much longer so I did a bench mark of running drush commands using shell aliases, the standard lando db-import, and finally the same drush shell alias used in the first test against Drupal VM set up with NFS.

For reference sake... `drush fresh` in my case runs the following:

```
$options['shell-aliases']['fresh'] = implode("\n", array(                       
  "!echo '\nDropping the database...'",                                         
  "drush sql-drop -y",                                                          
  "echo '\nImporting reference database...'",                                   
  "gunzip < ../reference/accme.sql.gz | drush sql-cli",                         
));
```

The following are the lowest benchmark on the same database I was importing which was 79MB...

```
$ time lando drush fresh

Dropping the database...
Do you really want to drop all tables in the database drupal7? (y/n): y

Importing reference database...

real    5m5.393s
user    0m0.724s
sys    0m0.080s
```

```
$ time lando db-import ../reference/accme-live-2017-11-01-08-13-04.sql.gz 
Preparing to import /app/web/../reference/accme-live-2017-11-01-08-13-04.sql.gz into drupal7 on database:3306 as drupal7...
Destroying all current tables in drupal7... 
NOTE: See the --no-wipe flag to avoid this step!
Dropping [...]
Gunzipped file detected!
Importing /app/web/../reference/accme-live-2017-11-01-08-13-04.sql.gz...
78.2MiB 0:04:56 [ 270KiB/s] [================================>] 100%            
Import completed with status code 0

real    5m19.920s
user    0m1.480s
sys    0m0.140s
```

``` 
time drush @accme.local fresh

Dropping the database...
Do you really want to drop all tables in the database drupal? (y/n): y

Importing reference database...

real    0m58.171s
user    0m0.072s
sys    0m0.128s
```

Any ideas? I know this is comparing a VM vs Docker solution... but is there any way we can speed this up from a 5 minutes? As you can see Drupal VM is only taking about 1 minute... and on larger databases this number seems to scale.
