### ISSUE TITLE
Lando version beta.29 and above does not find drush when running lando drush status

### ISSUE THREAD

**Issue by dandinu** [lando/pantheon#74]
Hi,

There is a problem with the latest versions of Lando (beta.29 through beta.31). When I run `lando drush status` I get:
```
The Drush launcher could not find a local Drush in your Drupal site.
Please add Drush with Composer to your project.
Run 'cd "/app" && composer require drush/drush'
```
![image](https://user-images.githubusercontent.com/939182/33894569-fadffb04-df66-11e7-9fcb-a833340b61fa.png)

The issue does not replicate on beta.28. It works without any issues there and I have no idea why.

Steps to replicate:

1. Run `lando start`
2. Run `lando drush status`
3. Get error

This is what `lando rebuild` says:
![image](https://user-images.githubusercontent.com/939182/33894793-8668bb7a-df67-11e7-8958-ffa728195ded.png)
I can clearly see `drush launcher` installing.

This is what the `.lando.yml` file looks like:
```
# Name the application the same as in your .platform.app.yaml.
name: app
# Use the recipe appropriate for your application.
recipe: drupal8

# The following additional build step will install the Platform CLI
# in the application container.
services:
  appserver:
    build:
      - "curl -sS https://platform.sh/cli/installer | php"

# The following entry creates a `lando platform` command that will run
# any Platform CLI command from inside the container if desired. 
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform
    options:
      passthrough: true
  sync:
    description: Execute script to sync files to the local machine.
    service: appserver
    cmd: /app/scripts/lando-scripts/sync.sh

config:
  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
  via: nginx

  # Set the webroot to match your .platform.app.yaml.
  webroot: web

  # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
  # Specify the version to match what's in services.yaml.
  database: mariadb:10.1
```

Do you have any ideas?
