### ISSUE TITLE
Add ability to use "Pantheon Search Connector" (Solr 8) for Pantheon recipe

### ISSUE THREAD

**Issue by Dishvola** [lando/pantheon#88]
So you use "Pantheon Search Connector" on production.

![Image 2021-12-10 at 1 37 17 PM](https://user-images.githubusercontent.com/1149440/145568670-0696e647-2939-4984-a356-4468d801d72e.jpg)

Then you spin up it locally via lando.

It looks like you should update your .lando file with something like this:
```
# Get nice url's for each service.
proxy:
  search:
    - solr.yoursite.lndo.site:8983

services:
  # Solr
  # Spin up a Solr container called "search".
  search:
    # Use a specific Solr version, same as the default one at the time of writing.
    type: solr:8.6
    # Optionally declare the name of the Solr core.
    # This setting is only applicable for versions 5.5 and above.
    core: lando
    # Optionally allow access at localhost:9999.
    # You will need to make sure port 9999 is open on your machine.
    # You can also set `portforward: true` to have Lando dynamically assign a port.
    # Unlike specifying an actual port setting this to true will give you
    # a different port every time you restart your app.
    portforward: 8983
    # Optionally use custom Solr config files eg (schema.xml and solrconfig.xml).
    # This is relative to the app root (which may be different from your webroot).
    # This should be the directory containing the schema.xml and solrconfig.xml files, not the path to a certain file.
    config:
      conf: web/modules/contrib/search_api_solr/solr-conf-templates/8.x
```

**BUT IT'S NOT WORKS FOR NOW.**

In my opinion we should add default env variables to the lando such as:
```
PANTHEON_INDEX_SCHEME
PANTHEON_INDEX_HOST
PANTHEON_INDEX_PORT
PANTHEON_INDEX_PATH
PANTHEON_INDEX_CORE
PANTHEON_INDEX_SCHEMA
```

The values should be the same as default lando solr 8 parameters, so you just enable solr 8 in your .lando file, then run `lando rebuild` and it should works as expected with "Pantheon Search Connector" locally.

Please provide that somehow :) Or please correct me if I am wrong somewhere.
Thanks!

**Comment by Dishvola** [comment]
Hm.... Looks like it should works by default when you just enable solr index `index: true` for pantheon receipt (for example):
```
name: sitename
recipe: pantheon
config:
  framework: drupal8
  site: sitename
  id: xxxxxxxxxxxxxxxxxxxxxxxxxxx
  webroot: web
  xdebug: true
  index: true
  edge: false
  cache: true
```
Lando should parse pantheon.yml, find out 
```
search:
  version: 8
```
and then do the magic :)

**I'm confusing and don't understand if it's a bug or feature request...**
